apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-api-dev
resources:
- ../../base
images:
- newTag: latest
- name: ghcr.io/Leam-Akuity/argo-samples
  newTag: latest
- name: ghcr.io/leam-akuity/argo-samples
